from button import Button
from config import GREEN, BUTTON_WIDTH, BUTTON_HEIGHT, BLACK, YELLOW, RED

# Init buttons
PAUSE_BUTTON = Button(10, 10, BUTTON_WIDTH, BUTTON_HEIGHT, "Pause", BLACK, RED)
SAVE_BUTTON = Button(10 + BUTTON_WIDTH + 10, 10, BUTTON_WIDTH, BUTTON_HEIGHT, "Save", BLACK, GREEN)
LOAD_BUTTON = Button(10 + 2 * (BUTTON_WIDTH + 10), 10, BUTTON_WIDTH, BUTTON_HEIGHT, "Load", BLACK, YELLOW)

